"""
vault-index: генератор .ai/VAULT-INDEX.md — сводка состояния vault.

Сканирует проекты, задачи, skills, bots и формирует
машиночитаемый индекс для progressive disclosure.

Запуск:
  .venv/bin/python -m tools.vault_index
"""

from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

VAULT_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT = VAULT_ROOT / ".ai" / "VAULT-INDEX.md"

SKIP_PROJECTS = {"_Архив", "_Demo"}


def _parse_task_status(task_md: Path) -> str:
    """Extract status from YAML frontmatter or ## Статус section."""
    try:
        text = task_md.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return "?"

    for m in re.finditer(r"^status:\s*[\"']?([^\"'\n]+)", text, re.MULTILINE):
        return m.group(1).strip()

    for m in re.finditer(r"\*\*Статус\*\*:\s*(.+)", text):
        return m.group(1).strip()

    return "?"


def _scan_projects() -> list[dict]:
    projects_dir = VAULT_ROOT / "Проекты"
    if not projects_dir.is_dir():
        return []

    results = []
    for pdir in sorted(projects_dir.iterdir()):
        if not pdir.is_dir() or pdir.name.startswith(".") or pdir.name in SKIP_PROJECTS:
            continue

        readme = pdir / "README.md"
        visibility = "?"
        if readme.is_file():
            try:
                content = readme.read_text(encoding="utf-8", errors="replace")
                m = re.search(r"[Вв]идимость[:\s]*\**\s*(командный|личный)", content)
                if m:
                    visibility = m.group(1)
            except OSError:
                pass

        tasks_dir = pdir / "Задачи"
        statuses: dict[str, int] = {}
        if tasks_dir.is_dir():
            for td in sorted(tasks_dir.iterdir()):
                if not td.is_dir():
                    continue
                task_file = td / "task.md"
                if task_file.is_file():
                    st = _parse_task_status(task_file)
                    statuses[st] = statuses.get(st, 0) + 1

        results.append({
            "name": pdir.name,
            "visibility": visibility,
            "statuses": statuses,
            "total_tasks": sum(statuses.values()),
        })

    return results


def _scan_skills(subdir: str) -> list[str]:
    skills_dir = VAULT_ROOT / ".ai" / "skills" / subdir
    if not skills_dir.is_dir():
        return []
    return sorted(f.name for f in skills_dir.iterdir() if f.suffix == ".md")


def _scan_rules() -> list[str]:
    rules_dir = VAULT_ROOT / ".ai" / "rules"
    if not rules_dir.is_dir():
        return []
    return sorted(f.name for f in rules_dir.iterdir() if f.suffix == ".md")


def _scan_knowledge() -> list[str]:
    knowledge_dir = VAULT_ROOT / ".ai" / "knowledge"
    if not knowledge_dir.is_dir():
        return []
    items = []
    for item in sorted(knowledge_dir.iterdir()):
        if item.is_file() and item.suffix == ".md":
            items.append(item.name)
        elif item.is_dir():
            items.append(f"{item.name}/")
    return items


def _format_status_summary(statuses: dict[str, int]) -> str:
    parts = []
    mapping = [
        ("выполнена", "done"),
        ("в процессе", "wip"),
        ("открыта", "open"),
        ("на холде", "hold"),
    ]
    for ru, short in mapping:
        count = statuses.get(ru, 0)
        if count:
            parts.append(f"{count} {short}")
    unknown = sum(v for k, v in statuses.items() if k not in dict(mapping))
    if unknown:
        parts.append(f"{unknown} ?")
    return ", ".join(parts) if parts else "—"


def generate() -> str:
    today = date.today().isoformat()
    projects = _scan_projects()
    core_skills = _scan_skills("core")
    domain_skills = _scan_skills("domain")
    rules = _scan_rules()
    knowledge = _scan_knowledge()

    lines = [
        "# VAULT-INDEX",
        "",
        f"> Auto-generated by `python -m tools.vault_index` on {today}",
        "> Do not edit manually — re-run the tool to update.",
        "",
        "## Проекты",
        "",
        "| Проект | Видимость | Задачи | Статусы |",
        "|--------|-----------|--------|---------|",
    ]

    for p in projects:
        statuses_str = _format_status_summary(p["statuses"])
        lines.append(f"| {p['name']} | {p['visibility']} | {p['total_tasks']} | {statuses_str} |")

    lines += [
        "",
        f"## .ai/skills/core/ ({len(core_skills)})",
        "",
    ]
    for s in core_skills:
        lines.append(f"- `{s}`")

    lines += [
        "",
        f"## .ai/skills/domain/ ({len(domain_skills)})",
        "",
    ]
    for s in domain_skills:
        lines.append(f"- `{s}`")

    lines += [
        "",
        f"## .ai/rules/ ({len(rules)})",
        "",
    ]
    for r in rules:
        lines.append(f"- `{r}`")

    lines += [
        "",
        f"## .ai/knowledge/ ({len(knowledge)})",
        "",
    ]
    for k in knowledge:
        lines.append(f"- `{k}`")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    content = generate()
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(VAULT_ROOT)} ({content.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
